
POST http://localhost:8080/api/v1/task
Accept: application/json
Content-Type: application/json

{
  "nameTask": "hola",
  "dueDate": "2012-12-12",
  "status": "string",
  "userId": 1,
  "etiquetaId": 1
}
